# Generated by Django 4.1.3 on 2023-02-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watercanapp', '0003_com_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('contact_number', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
    ]
