# Generated by Django 4.1.7 on 2023-02-20 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watercanapp', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usr_can_odr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('phone_no', models.CharField(max_length=13)),
                ('adress', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField(max_length=150)),
                ('usr_can', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
