# Generated by Django 4.1.7 on 2023-02-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watercanapp', '0006_delivered_his_delete_com_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='com_can_odr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
