# Generated by Django 4.1.7 on 2023-02-20 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watercanapp', '0008_com_can_odr_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='com_can_odr',
            name='com_can',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
