# Generated by Django 4.1.7 on 2023-02-20 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watercanapp', '0009_com_can_odr_com_can'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivered_his',
            name='delv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
